uvmf:
  environments:
    memaccess:
      agents:
      - initiator_responder: RESPONDER
        name: memaccess_in_agent
        type: memaccess_in
      - initiator_responder: RESPONDER
        name: memaccess_out_agent
        type: memaccess_out
      analysis_components:
      - name: memacc_pred
        parameters: []
        type: memaccess_predictor
      - name: memacc_cov
        parameters: []
        type: memaccess_coverage
      analysis_exports: []
      analysis_ports:
      - connected_to: memaccess_in_agent.monitored_ap
        name: memaccess_in_ap
        trans_type: memaccess_in_transaction
      - connected_to: memaccess_out_agent.monitored_ap
        name: memaccess_out_ap
        trans_type: memaccess_out_transaction
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: memacc_sb
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: memaccess_out_transaction
      subenvs: []
      tlm_connections:
      - driver: memaccess_in_agent.monitored_ap
        receiver: memacc_pred.memaccess_in_ae
        validate: 'True'
      - driver: memacc_pred.memaccess_out_sb_ap
        receiver: memacc_sb.expected_analysis_export
        validate: 'True'
      - driver: memaccess_out_agent.monitored_ap
        receiver: memacc_sb.actual_analysis_export
        validate: 'True'
      - driver: memaccess_in_agent.monitored_ap
        receiver: memacc_cov.memaccess_in_ae
        validate: 'True'
      - driver: memaccess_out_agent.monitored_ap
        receiver: memacc_cov.memaccess_out_ae
        validate: 'True'
