uvmf:
  environments:
    lc3:
      agents:
      - initiator_responder: RESPONDER
        name: inst_mem_agent
        type: inst_mem
      - initiator_responder: RESPONDER
        name: data_mem_agent
        type: data_mem
      analysis_components: []
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: fetch_env_pkg
      - name: decode_env_pkg
      - name: writeback_env_pkg
      - name: memaccess_env_pkg
      - name: control_env_pkg
      - name: execute_env_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: fetch_env
        parameters: []
        reg_block_instance_name: fetch_env_rm
        type: fetch
      - name: decode_env
        parameters: []
        reg_block_instance_name: decode_env_rm
        type: decode
      - name: writeback_env
        parameters: []
        reg_block_instance_name: writeback_env_rm
        type: writeback
      - name: memaccess_env
        parameters: []
        reg_block_instance_name: memaccess_env_rm
        type: memaccess
      - name: control_env
        parameters: []
        reg_block_instance_name: control_env_rm
        type: control
      - name: execute_env
        parameters: []
        reg_block_instance_name: execute_env_rm
        type: execute
      tlm_connections: []
