uvmf:
  environments:
    fetch:
      agents:
      - initiator_responder: INITIATOR
        name: fetch_in_agent
        type: fetch_in
      - initiator_responder: RESPONDER # should be INITIATOR, Made a manual change in code
        name: fetch_out_agent
        type: fetch_out
      analysis_components:
      - name: fetch_pred
        type: fetch_predictor
      
      analysis_exports: []
      analysis_ports: []

      config_constraints: []
      config_vars: []

      existing_library_component: 'False'

      parameters: []

      scoreboards:
      - name: fetch_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: fetch_out_transaction
      subenvs: []
      tlm_connections:
      - driver: fetch_in_agent.monitored_ap
        receiver: fetch_pred.fetch_in_agent_ae
      - driver: fetch_pred.fetch_sb_ap
        receiver: fetch_sb.expected_analysis_export
      - driver: fetch_out_agent.monitored_ap
        receiver: fetch_sb.actual_analysis_export
